### PR TITLE
AnguishedParrot - Update all the configs

### PR DESCRIPTION
**Pull request by allanhortle**
# Webpack
- [ ] make a client and a server version
- [ ] let the use choose which loaders
- [ ] add mjs loader
- [ ] add mdx loader
- [ ] can i use lite is out of date WTF???

# Flow
- [x] update
- [x] include jest lib that matches the jest version installed by blueflag-test
- [x] complain if flow coverage is too low

# Eslint
- [x] eslint doesnt support enzyme
- [x] eslint doesnt support jest
- [x] dont complain about missing types

# Babel
- [x] babel preset doesn't extract flow types
- [x] add babel-plugin-graphql-tag

# Jest
- [x] cant test hooks
- [x] no node version of the testing config
- [x] test should support `__test__` and `__tests__`

### CODE REVIEW

**Comment by dancoates** [comment]
The dodgy extending of webpack is one that would be good to fix:

```js
    // @TODO update blueflag-webpack so that it doesn't always include the HTML plugin
    config.plugins.splice(2);

    // Allow warmup plugin to work
    config.plugins.push(new CopyWebpackPlugin([{from: '_warmup', to: '_warmup'}]));

    // Ignore pg-native to stop build breaking
    config.plugins.push(new webpack.IgnorePlugin(/^pg-native$/));

    // Overwrite SASS loader setup, because it uses style-loader which is incompatible with SSR
    config.module.rules[3] = {
        test: /\.scss$/,
        use: [
            "css-loader",
            "sass-loader"
        ]
    };

    config.module.rules[2] = {
        test: /\.(png|svg|jpg|gif|ttf|woff|woff2|eot|otf|ico)$/,
        use: {
            loader: 'url-loader'
        }
    };
```

**Comment by dancoates** [comment]
Not sure if it is actually needed but I have eslintrc files that add the jest plugin:

```
{
  "extends": [
      "eslint-config-blueflag",
      "eslint-config-blueflag/flow"
  ],
  "plugins": ["jest"],
  "env": {
      "jest": true
  }
}

```

that should be enabled by default probably?

**Comment by dancoates** [comment]
Also I think I'm not using babel-preset-blueflag any more. Can't remember why but the babelrc for backend stuff it just

```json
{
    "presets": [
        ["@babel/preset-env", {
            "targets": {
                "node": "8.10"
            }
        }],
        "@babel/preset-flow"
    ],
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-class-properties",
        "babel-plugin-graphql-tag"
    ]
}

```

**Comment by dxinteractive** [comment]
Webpack config should contain mjs loader by default

```
const MJS_LOADER = {
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
    };
```

**Comment by dxinteractive** [comment]
I often add `MDX_LOADER`, but its such a specific set of nonsense I'm not sure if it's goo to put it in the actual config. Or, if there were a way to say "this is out specific set of MDX nonsense, use it if you really want" then that would be good.

**Comment by dxinteractive** [comment]
Just looking at examples on serverside, I ended up not using proto-webpack at all because it was too different. Maybe we could have a server one? Here's mine:

```
/* eslint-disable flowtype/require-valid-file-annotation */
const path = require('path');
const webpack = require('webpack');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = function() {
    const mode = process.env.NODE_ENV === 'production' ? 'production' : 'development';
    const production = mode === 'production';

    const src = path.resolve('src');
    const dest = path.resolve('dist');

    // @INTENT: use babel on js/jsx files
    const JS_LOADER = {
        test: /\.js$/,
        include: [src],
        use: {
            loader: 'babel-loader',
            options: {
                cacheDirectory: true
            }
        }
    };

    // @INTENT: load graphql files raw style
    const GRAPHQL_LOADER = {
        test: /\.graphql$/,
        include: [src],
        use: 'raw-loader'
    };

    return {
        mode,
        cache: production,
        devtool: production ? 'source-map' : undefined,
        entry: {
            api: './src/index.js',
            permissionsGenerator: './src/permissions-generator/index.js'
        },
        target: 'node',
        output: {
            libraryTarget: 'commonjs2',
            path: dest,
            filename: '[name].js'
        },
        resolve: {
            alias: {
                ['graphql-service-utils']:  path.resolve(src, 'graphql-service-utils'),
                ['mitsubishi-graphql-api']:  path.resolve(src, 'mitsubishi-graphql-api'),
                ['permissions-generator']:  path.resolve(src, 'permissions-generator'),
                ['environment']:  path.resolve(src, 'environment'),
                ['services']:  path.resolve(src, 'services')
            },
            extensions: ['.js']
        },
        plugins: [
            new CleanWebpackPlugin([dest], {
                root: path.resolve(dest, '..'),
                verbose: true,
                allowExternal: true
            }),
            new webpack.IgnorePlugin(/\.flow$/)

        ].filter(ii => ii),
        module: {
            rules: [
                JS_LOADER,
                GRAPHQL_LOADER
            ]
        }
    };
}();

```

**Comment by dxinteractive** [comment]
I find I'm setting tests to `testEnvironment: 'node',` on server

**Comment by dxinteractive** [comment]
Client specific eslint should contain this if possible

```
{
    "settings": {
        "react": {
            "version": "detect"
        }
    }
}

```

**Comment by dxinteractive** [comment]
Server eslint still wants this even if you're not using react:
```
{
    "settings": {
        "react": {
            "version": "detect"
        }
    }
}

```

**Pull request closed without merging**
